import type { Metadata } from "next";
import "./globals.css";
import { robotoSlab } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        {children}
        <img src="/background.jpg" alt="background" className="fixed inset-0 w-full h-full object-cover z-0" />
      </body>
    </html>
  );
}
